services:
  family-tuner-server:
    container_name: family-tuner-server
    networks:
      - family-tuner_network
    build:
      context: .
    environment:
      DB_NAME: $DB_NAME
      POST: $PORT
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      WEB_APP_URL: $WEB_APP_URL
      MONGO_URL: $MONGO_URL
    ports:
      - 5004:5000
    restart: unless-stopped

  family-tuner-mongodb:
    image: mongo:latest
    container_name: family-tuner-mongodb
    ports:
      - "27017:27017"
    volumes:
      - family-tuner-mongodb-data:/data/db
    networks:
      - family-tuner_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    restart: unless-stopped

volumes:
  family-tuner-mongodb-data:

networks:
  family-tuner_network:
    name: family-tuner_network
